keys: &keys
  app_id: 164243886936118
  app_secret: 1cefe1e9f46ccefc9ac09abb692a8500
  
development:
  <<: *keys

test:
  <<: *keys
  
cucumber:
  <<: *keys


production:
  app_id: 164243886936118
  app_secret: 1cefe1e9f46ccefc9ac09abb692a8500